name: "Check docs"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v1
        - name: Install recommonmark
          run: |
            pip install recommonmark
        - uses: ammaraskar/sphinx-action@master
          with:
            docs-folder: "docs/"