name: "Check docs"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install recommonmark
        run: |
          pip install sphinx recommonmark
      - name: check docs
        run: |
          cd ${GITHUB_WORKSPACE}
          make html
